name: Build Minecraft Client

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo çek
        uses: actions/checkout@v3

      - name: Java kur
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle izin fix
        run: chmod +x gradlew

      - name: Build al
        run: ./gradlew build --no-daemon

      - name: Jar upload
        uses: actions/upload-artifact@v3
        with:
          name: client-jar
          path: build/libs/*.jar
